### ISSUE TITLE
Issue with clearDisplay()

### ISSUE THREAD

**Issue by kbowerma** [Seeed-Studio/OLED_Display_96X96#1]
it seems like clearDisplay() should clear the whole screen but mine is only clearing the line of the last setTextXY() in order for me to clear the whole I need to seTextXY() to every row I have moved the curso to and run clearDisplay.

It is acting more like a clearCurrentRow()

I also looked at the function and it looks like it is only sending data to the first six rows  ( ```j<48) but that does not seem to comply with the behavior either.

```
void SeeedGrayOLED::clearDisplay()
{
    unsigned char i,j;
    for(j=0;j<48;j++)
    {
        for(i=0;i<96;i++)  //clear all columns
        {
            sendData(0x00);
        }
    }

}
```

Thanks

**Comment by songshu** [comment]
You might need to reinitialize the rows and columns againas it sounds like the map is set to 2 rows for you instead of the whole screen.   Look at init().  It's 96 lines x 48 bytes (2 nibbles: each 4 bits identifies brightness level of that pixel on that row).
