### ISSUE TITLE
putFloat undefined in cpp file

### ISSUE THREAD

**Issue by bat-007** [Seeed-Studio/OLED_Display_96X96#10]
Hello!

It seems that someone came across this same issue years ago, but the putFloat function is undefined in the cpp. file that I have downloaded. I might not have the correct file, but I did install it from Arduino IDE directly. The putFloat function is used in the header file, but it is not referenced at all in the cpp. I am assuming this is why I keep getting an "undefined reference to" error. I would add the necessary code to the cpp. myself but I have only been coding for a grand total of a week and a half and don't want to accidentally mess up the cpp.

**Comment by bat-007** [comment]
Hello!

I was able to find a different library that had the float defined in the .cpp file so all is well thanks!

**Comment by ackPeng** [comment]
@bat-007 Thank you very much for your question. If you have any questions, please contact us for discussion.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
