### ISSUE TITLE
Document complicated behavior

### ISSUE THREAD

**Issue by dsjove** [Seeed-Studio/OLED_Display_96X96#4]
Thank you for taking the time to post the cpp code for the SH1107G chipset. I keep trying to figure out the logic in drawBitmap. Logic for the scan pattern, bit composition, and framing the source are in there but I am having trouble differentiating them. Would you be able to document the source?

**Comment by KillingJacky** [comment]
Hi @dsjove , as the open source contributor, we're in the same line, we understand from the original's documentations and utilize the products based on them, here're some resources helpful for you.
- https://github.com/SeeedDocument/Grove_OLED_1.12/raw/master/resources/SH1107G_datasheet.pdf
- http://wiki.seeed.cc/Grove-OLED_Display_1.12inch/

**Comment by dsjove** [comment]
I appreciate the response. I have previously read through the documentation without coming to an understanding of the data format and scan pattern we must use when communicating over the i2C bus. A few well placed comments in your open source code would go a long way to extend the existing documentation.
