### ISSUE TITLE
void SeeedGrayOLED::drawBitmap(const unsigned char *bitmaparray,int bytes)

### ISSUE THREAD

**Issue by JBleckmann** [Seeed-Studio/OLED_Display_96X96#6]
Hi.
Great simple library for OLED with SSD1327. I found small issue in void SeeedGrayOLED::drawBitmap(const unsigned char *bitmaparray,int bytes). 
I need to change nibble order as pixels are swapped. You can see it if odd and even pixel are different.
If not you cannot recognize.

origin 
        char bit1=pgm_read_byte(&bitmaparray[i]) << j  & 0x80;
        char bit2=pgm_read_byte(&bitmaparray[i]) << (j+1) & 0x80;

updated
        char bit2=pgm_read_byte(&bitmaparray[i]) << j  & 0x80;
        char bit1=pgm_read_byte(&bitmaparray[i]) << (j+1) & 0x80;

Thanks, I safe a lot of time with your library.

**Comment by KillingJacky** [comment]
Hi @JBleckmann , do you mean that is a common issue, or just for some special cases? I can't get what  `You can see it if odd and even pixel are different.` mean.

**Comment by JBleckmann** [comment]
Hi KillingJacky , as example, 6 pixel in one line, 3 on, 3 off. 000XXX. With orgin code I see 00X0XX.
That's why I update code.
